name:                local-from-hackage-without-tarball
version:             0.1.0.0
github:              "JoergBrueggmann/local-from-hackage-without-tarball"
license:             BSD3
author:              "Jörg K.-H. W. Brüggmann"
maintainer:          "info@joerg-brueggmann.de"
copyright:           "2024 Jörg K.-H. W. Brüggmann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JoergBrueggmann/local-from-hackage-without-tarball#README.md>

dependencies:
- base >= 4.7 && < 5
- random == 1.2.1

library:
  source-dirs: src

executables:
  local-from-hackage-without-tarball:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - local-from-hackage-without-tarball

tests:
  local-from-hackage-without-tarball-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - local-from-hackage-without-tarball
