#!/bin/bash

# Builds and executes the application

echo "build and execute application"

./info.sh $1

name=`cat ./info/name.txt`
os=`cat ./info/os.txt`

echo "application:"$name

rm -v "./"$name".cabal"
stack build

if [ $os == "win" ]; then
    stack exec $name".exe"
else
    stack exec $name
fi
